### ISSUE TITLE
Incorrect ``unique`` result for column with numerical name

### ISSUE THREAD

**Issue by rjzamora** [dask/dask-expr#1015]
I'm getting an incorrect `unique` result after selecting a numerical column name from a `DataFrame` collection:

```python
import pandas as pd
import dask.dataframe as dd

pdf = pd.DataFrame({1: [0,3,0,1,2,0,3,1,1]})
df = dd.from_pandas(pdf, 3)

df[key].unique().compute()
```
```
0    0
1    1
2    3
0    3
1    2
2    0
3    1
Name: 1, dtype: int64
```

I haven't had time to dig into this yet, but it seems like things work fine when the column name is `0`. Also, changing the shuffle algorithm doesn't seem to resolve the issue.

**Comment by phofl** [comment]
0 only worked by accident :)

**Comment by rjzamora** [comment]
>0 only worked by accident :)

Heh - Yeah, I just discovered the same thing. Doesn't seem like there is support for `int` column names at the moment.

**Comment by phofl** [comment]
Not if you shuffle there (but my pr addresses it)
