### ISSUE TITLE
Array: Unify Chunks

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-expr#1096]
There's a pretty major TODO in the array implementation, to implement `unify_chunks`, the code that takes two arrays of possibly different chunking / dimensions, and aligns them so their chunking corresponds.  There are several TODO notes in `blockwise.py` around this as the `align_arrays=` keyword.  

My recollection is that this was the biggest missing piece (among several missing pieces) that stopped the implementation from being somewhat useful.

No urgency of course, just highlighting where I think the next big step might be.

**Comment by phofl** [comment]
that's done now
