### ISSUE TITLE
Please list test dependencies explicitly

### ISSUE THREAD

**Issue by penguinpee** [dask/dask-expr#1102]
The most recent release, `1.1.7`, introduced `xarray` as a dependency for running tests (3997b82). Yet, nowhere is that dependency mentioned, except in ci/environment.yml, which is not an obvious place. Nor is `xarray` a dependency of one of the packages `dask-expr` depends on.

Having test dependencies listed in either a requirements file or in a dedicated extra in `pyproject.toml`, allows our tooling to take care of it instead of manually having to intervene whenever dependencies change.

Alternatively, make tests depending on extra modules soft fail if the module is not available.

**Comment by fjetter** [comment]
> Alternatively, make tests depending on extra modules soft fail if the module is not available.

This is how we're typically doing this in other dask libraries. Are you interested in contributing a patch?
