### ISSUE TITLE
Add dask-expr support to IO connectors not in dask/dask

### ISSUE THREAD

**Issue by phofl** [dask/dask-expr#675]
- [ ] dask-bigquery
- [x] dask-deltatable
- [x] Dask-snowflake 

are those that come to mind

**Comment by alex-rakowski** [comment]
PR: dask-snowflake - https://github.com/coiled/dask-snowflake/pull/60.

**Comment by alex-rakowski** [comment]
[related issue](https://github.com/coiled/customer-success/issues/246)

**Comment by alex-rakowski** [comment]
snowflake is merged

**Comment by fjetter** [comment]
We had issues with dask-bigquery and are not doing this now.

@phofl you mentioned that you wanted to take care of deltatable. is this still correct?

**Comment by fjetter** [comment]
@jrbourbeau maybe you can have a loop at the bigquery instead? (I thin kyou set this up originally, didn't you? We have issues with failing CI)

**Comment by jrbourbeau** [comment]
IIRC I wasn't really involved with the dask-bigquery efforts, but I'm happy to take a look. Do you have a link to the CI issues?
