### ISSUE TITLE
Maybe support attribute assignment?

### ISSUE THREAD

**Issue by phofl** [dask/dask-expr#785]
See ``test_attribute_assignment`` in dask/dask

```

df.a = df.b+df.c
```

I am not sure if this even should work, but it does in dask/dask

**Comment by fjetter** [comment]
Looking at pandas...

>  UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

New assignments will be removed from pandas as well so if it's just about that I suggest to not bother with it.

Assignments to columns that already exists is _maybe_ something we'd want to do

**Comment by phofl** [comment]
Yeah just making it explicit: This issue was supposed to cover both.

Let's just focus on existing columns then

**Comment by phofl** [comment]
fixed by #1011
