### ISSUE TITLE
DataFrame.divisions are lost on persist()

### ISSUE THREAD

**Issue by luxcem** [dask/dask-expr#976]
**Describe the issue**:
DataFrame divisions are set to None on persist()

**Minimal Complete Verifiable Example**:

```python
df = pd.DataFrame(np.random.randint(0, 20000, size=(10, 3)), columns=list('ABC'))
ddf = dd.from_pandas(df)
print(ddf.divisions) # (0, 9)

ddf = dd.from_pandas(df)
ddf = ddf.reset_index().set_index("A", sort=True, npartitions=2)
print(ddf.divisions) # (641, 19218)

ddf = ddf.persist()
print(ddf.divisions) # (None, None)
```

**Environment**:

- Dask version: `2024.3.0`
- Python version: `3.12.2`
- Operating System: OSX
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Thx, opened a PR to fix
