### ISSUE TITLE
repartition with divisions when know_divisions is False raise an exception.

### ISSUE THREAD

**Issue by luxcem** [dask/dask-expr#979]
**Describe the issue**: When `repartion` is called with `divisions` and the divisions are not known it will raise a ValueError.
The code in https://github.com/dask/dask-expr/blob/main/dask_expr/_repartition.py assumes that the old divisions are known.

**Minimal Complete Verifiable Example**:

```python
df = pd.DataFrame(np.random.randint(0, 100, size=(10, 3)), columns=list('ABC'))
ddf = dd.from_pandas(df)
ddf = ddf.reset_index().set_index("A", sort=True, npartitions=1) # Ensure not know_divisions
assert not ddf.known_divisions
divisions = ddf.compute_current_divisions() # for convenience but any divisions will raise an exception
assert ddf.divisions == (None, None)
ddf.repartition(divisions=divisions).compute() # raise ValueError
```

Raises `ValueError: left side of old and new divisions are different ` https://github.com/dask/dask-expr/blob/main/dask_expr/_repartition.py#L254

**Anything else we need to know?**: Follow up for #975 with a practical example of code where divisions are needed.

**Environment**: 

- Dask version: 2024.3.0
- Python version: 3.12.2
- Operating System: OSX
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
I'll update the error message, it is very awkward at the moment. But the behaviour is consistent with the old implementation
